[package]
name = "OpenCharting"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.13.1", features = ["tokio"]}
serde_json = "1.0.133"
tokio = {version = "1.41.1", features = ["full"]}
tokio-tungstenite = {version = "0.24.0", features = ["native-tls"]}
futures-util = "0.3.31"
